Name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 */6 * * *"  # كيعاود يخدم كل 6 سوايع

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 350 

    permissions:
      id-token: write
      contents: read
      actions: write

    steps:
      # 1. إلغاء أي تشغيل قديم
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      # 2. نسخ الملفات
      - name: Clone repository
        uses: actions/checkout@v4

      # 3. تثبيت Node.js نسخة 20
      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 4. تثبيت أداة Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # 5. الكاش ديال الكود
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 6. تثبيت المكتبات
      - name: Install Dependencies
        run: npm install

      # 7. تشغيل مشروع البوت مع تمرير المتغيرات من GitHub Secrets
      - name: Start Project
        timeout-minutes: 345 
        env:
          # هنا كنمررو الرابط السري ديال MongoDB والـ Port للبوت فاش يبغي يخدم
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PORT: 5000
          PHONE_NUMBER: 212637904038
        run: npm run start
